name: .NET Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'   # change if you use .NET 6 or 7

      - name: Restore dependencies
        run: dotnet restore src/MyApp/MyApp.csproj

      - name: Build
        run: dotnet build src/MyApp/MyApp.csproj --no-restore --configuration Release

      - name: Test
        run: dotnet test src/MyApp/MyApp.csproj --no-build --verbosity normal
