name: PR Workflow

on:
  pull_request:
    types:
      - closed

jobs:
  delete-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Delete Source Branch
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GHCR_TOKEN }}
          script: |
            const branch = context.payload.pull_request.head.ref;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            
            // Skip deletion of protected branches
            if (branch === 'main' || branch === 'master') {
              console.log(`Skipping deletion of protected branch: ${branch}`);
              return;
            }
            
            try {
              await github.rest.git.deleteRef({
                owner: owner,
                repo: repo,
                ref: `heads/${branch}`
              });
              console.log(`Successfully deleted branch: ${branch}`);
            } catch (error) {
              console.log(`Branch ${branch} was already deleted or is protected`);
            }
